import { Option } from '@/lib/types'

export const oblastValue = [
	'lviv',
	'ivano-frankivsk',
	'ternopil',
	'zakarpatska',
	'volyn',
	'rivne',
	'chernivtsi',
	'khmelnytskyi',
	'kyivska',
	'vinnytsia',
	'zhytomyr',
	'poltava',
	'cherkasy',
	'kirovohrad',
	'kyiv',
	'odesa',
	'mykolaiv',
	'kherson',
	'kharkiv',
	'donetsk',
	'luhansk',
	'sumy',
	'chernihiv',
	'zaporizhzhia',
	'dnipro',
] as const

export const oblastOptions: Option[] = [
	{ label: 'Захід', value: 'west', isHeader: true },
	{ label: 'Львівська', value: 'lviv' },
	{ label: 'Івано-Франківська', value: 'ivano-frankivsk' },
	{ label: 'Тернопільська', value: 'ternopil' },
	{ label: 'Закарпатська', value: 'zakarpatska' },
	{ label: 'Волинська', value: 'volyn' },
	{ label: 'Рівненська', value: 'rivne' },
	{ label: 'Чернівецька', value: 'chernivtsi' },
	{ label: 'Хмельницька', value: 'khmelnytskyi' },

	{ label: 'Центр', value: 'center', isHeader: true },
	{ label: 'Київська', value: 'kyivska' },
	{ label: 'Вінницька', value: 'vinnytsia' },
	{ label: 'Житомирська', value: 'zhytomyr' },
	{ label: 'Полтавська', value: 'poltava' },
	{ label: 'Черкаська', value: 'cherkasy' },
	{ label: 'Кіровоградська', value: 'kirovohrad' },
	{ label: 'м. Київ', value: 'kyiv' },

	{ label: 'Південь', value: 'south', isHeader: true },
	{ label: 'Одеська', value: 'odesa' },
	{ label: 'Миколаївська', value: 'mykolaiv' },
	{ label: 'Херсонська', value: 'kherson' },

	{ label: 'Схід', value: 'east', isHeader: true },
	{ label: 'Харківська', value: 'kharkiv' },
	{ label: 'Донецька', value: 'donetsk' },
	{ label: 'Луганська', value: 'luhansk' },

	{ label: 'Північ', value: 'north', isHeader: true },
	{ label: 'Сумська', value: 'sumy' },
	{ label: 'Чернігівська', value: 'chernihiv' },
	{ label: 'Запорізька', value: 'zaporizhzhia' },
	{ label: 'Дніпропетровська', value: 'dnipro' },
]
